services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: AndroidVizChemLab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/AndroidVizChemLab
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      GIGACHAT_CLIENT_ID: ${GIGACHAT_CLIENT_ID}
      GIGACHAT_AUTH_KEY: ${GIGACHAT_AUTH_KEY}
      GIGACHAT_SCOPE: GIGACHAT_API_PERS
    depends_on:
      - db

volumes:
  pgdata:
