spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/AndroidVizChemLab}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.xml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8081
  address: 0.0.0.0