
gigachat.client-id=${GIGACHAT_CLIENT_ID}
gigachat.auth-key=${GIGACHAT_AUTH_KEY}
gigachat.scope=${GIGACHAT_SCOPE:GIGACHAT_API_PERS}

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

server.port=8081


